spring:
  application:
    name: eureka-service-1
server:
  port: 8880
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true
    fetch-registry: true
  server:
    enableSelfPreservation: false
logging:
  level:
    root: debug
