spring:
  application:
    name: eureka-service
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8887/eureka/
    register-with-eureka: false
    fetch-registry: false